ansible -i bizotdcinv ocpstonodes -m shell -a "systemctl stop glusterd"
ansible -i bizotdcinv ocpstonodes -m shell -a "rm -rf /var/lib/heketi /etc/glusterfs /var/lib/glusterd /var/log/glusterfs"
ansible -i bizotdcinv ocpstonodes -m shell -a "wipefs -a -f /dev/vdb"
ansible -i bizotdcinv ocpstonodes -m shell -a "yum remove redhat-storage-server -y"
ansible -i bizotdcinv ocpstonodes -m shell -a "yum remove gluster* -y"
ansible -i bizotdcinv ocpstonodes -m shell -a "yum install redhat-storage-server -y"
ansible -i bizotdcinv ocpstonodes -m shell -a "yum install gluster-block -y"
ansible -i bizotdcinv ocpstonodes -m shell -a "systemctl enable glusterd"
ansible -i bizotdcinv ocpstonodes -m shell -a "systemctl start glusterd"
