---
- name: copy sudo file + ssh key
  gather_facts: True
  hosts: allnodes
  become: no
  tasks:
    - name: Copy sudo file
      copy:
        src: ../files/sudo/ocpsudo
        dest: /etc/sudoers.d/ocpsudo
        owner: root
        group: root
        mode: 0600
    - name: Set authorized key taken from file
      authorized_key:
        user: ocpadmin
        state: present
        key: "{{ lookup('file', '../files/ssh/key') }}"
